apps/users/urls.py
from django.conf.urls import url
from . import views

app_name='users'
urlpatterns = [
  url(r'^$', views.index, name='home'),
  url(r'^log_in$', views.log_in, name='login'),
  url(r'^logout$', views.logout, name='logout'),
  url(r'^register$', views.register, name='register'),
  url(r'^register/add_user$', views.add_user, name='addUser'),
  url(r'^users/(?P<id>\d+)$', views.show_user, name='user'),
]

beltExam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^travels/', include('apps.travels.urls', namespace='travel')),
    url(r'^admin/', admin.site.urls),
]

apps/users/models.py
from __future__ import unicode_literals
import bcrypt
import re
from django.db import models


EMAIL_REGEX = re.compile(r'[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.+_-]+\.[a-zA-Z]+$')
NAME_REGEX = re.compile(r'[a-zA-Z0-9.,-]*$')
# Create your models here.
class UserManager(models.Manager):
  def login(self, postData):
    username = postData['username']
    password = postData['password']
  
    try:
      user = User.objects.get(username=username.lower())
      new_hash = bcrypt.hashpw(password.encode(), user.password.encode())

      if(new_hash == user.password):
        return [True, user]

      else:
        return [False, "Password doens't match username"]
     
    except:
      return [False, "Incorrect Username/Password"]

  def register(self, postData):
    user_valid = {'valid':True, 'errors':[], 'user':None}

    try:
      User.objects.get(username=postData['username'].lower())
      user_valid['valid']=False
      user_valid['errors'].append('Username Taken')

    except:
      pass
    
    try:
      User.objects.get(email=postData['email'].lower())
      user_valid['valid']=False
      user_valid['errors'].append('Email Taken')
    
    except:
      pass


    email = str(postData['email'].lower())
    if(not EMAIL_REGEX.match(email)):
      user_valid['valid']=False
      user_valid['errors'].append('Please enter a valid email')


    first_name = postData['first_name']
    if(len(first_name) < 3) or (not NAME_REGEX.match(first_name)):
      user_valid['valid']=False
      user_valid['errors'].append('Please enter a valid first name')


    last_name = postData['last_name']
    if(len(last_name) < 2) or (not NAME_REGEX.match(last_name)):
      user_valid['valid']=False
      user_valid['errors'].append('Please enter a valid last name')

    username = postData['username'].lower()
    if(str(username) == '') or (not NAME_REGEX.match(first_name)):
      user_valid['valid']=False
      user_valid['errors'].append('Please enter a username')

    clearPassNoHash = postData['password']
    if(len(clearPassNoHash)<8):
      user_valid['valid']=False
      user_valid['errors'].append('Password must be 8 characters or more')
   
    if(user_valid['valid']):
      clearPassNoHash = clearPassNoHash.encode()
      hashPass = bcrypt.hashpw(clearPassNoHash, bcrypt.gensalt())
      user = User.objects.create(first_name=str(first_name), 
                                 last_name=str(last_name), 
                                 username=username, 
                                 email=str(email).lower(), 
                                 password=hashPass
      )

      user.save()
      user_valid['user'] = user

    for error in user_valid['errors']:
      print(error)

    return user_valid

class User(models.Model):
  first_name = models.CharField(max_length=45)
  last_name = models.CharField(max_length=45)
  username = models.CharField(max_length=45)
  email = models.CharField(max_length=100)
  password = models.CharField(max_length=100)
  objects = UserManager()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

apps/users/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import *
# Create your views here.


def index(request):
    try:
      if(request.session['user_logged']):
        return redirect(reverse('books:home', kwargs={'id':request.session['user_id']}))

    except:
      pass

    request.session['user_logged'] = False
    request.session['user_id'] = None
    return render(request, "users/index.html")

def log_in(request):
    user_valid = User.objects.login(dict(request.POST.items()))
    if(user_valid[0]):
      request.session['user_logged'] = True
      request.session['user_id'] = user_valid[1].id
      return redirect('travel:home')
    else:
      messages.add_message(request, messages.INFO, user_valid[1])
      return redirect('users:home')
    

def register(request):
    return render(request, "users/register.html")

def add_user(request):
    user_valid = User.objects.register(dict(request.POST.items()))
    if(user_valid['valid']):
      messages.add_message(request, messages.INFO, 'Thanks for registering!', extra_tags='registered')
      return redirect('users:home')

    else:
      for message in user_valid['errors']:
        messages.add_message(request, messages.INFO, message)
      return redirect('users:register')

def logout(request):

    request.session.flush()
    return render(request, 'users/logout.html')

def show_user(request, id):
    try:
      if(request.session['user_logged']):
        user_id = request.session['user_id']

      else:
        return redirect('users:home')

    except:
      return redirect('users:home')

    context = {
      'user': User.objects.get(id=id),
    }
    return render(request, "users/user_page.html", context)

apps/users/templates/users/index.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'users/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <h1 class='greeting'>Belt Exam</h1>
  <div class='login_box'>
    <form action="{% url 'users:login' %}" method='post'>
    {% csrf_token %}
      <table>
        <tr>
          <td><input type='text' name='username' placeholder='User Name' class='user_field'></td>
        </tr>
        <tr>
          <td><input type='password' name='password' placeholder='Password' class='user_field'></td>
        </tr>
      </table>
      <input type='submit' value='Log In' class='login_button'>
      <a href="{% url 'users:register' %}" class='register_link'>Not a user? Register now!</a>
    </form>
    {% if messages %}
      {% for message in messages %}
        {% if 'registered' in message.tags %}
           <div class='message_box green'>
              <p class='message'>{{ message }}</p>
           </div>
        {% else %}
          <div class='message_box red'>
            <p class='message'>{{ message }}</p> 
           </div> 
        {% endif %}
      {% endfor %}
    {% endif %}
  </div>
</body>
</html>

apps/users/templates/users/logout.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'users/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<div class='header'>
  <h1 class='greeting'>Belt Exam</h1>
</div>
<body>
  <h1 class='greeting'>Log Out successful</h1>
  <form action='/'>
    <input type='submit' value='Back to Home Page'>
  </form>
</body>
</html>

apps/users/templates/users/register.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'users/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
  <h1>Belt Exam</h1>


  <div class='register_box'>
    <form action="{% url 'users:addUser' %}" method='post'>
    {% csrf_token %}
      <table>
        <tr>
          <td><p class='info'>First Name:</p></td>
          <td><input type='text' name='first_name' value='' class='user_field'></td>
        </tr>
        <tr>
          <td><p class='info'>Last Name:</p></td>
          <td><input type='text' name='last_name' value='' class='user_field'></td>
        </tr>
        <tr>
          <td><p class='info'>Username:</p></td>
          <td><input type='text' name='username' value='' class='user_field'></td>
        </tr>
        <tr>
          <td><p class='info'>Email:</p></td>
          <td><input type='email' name='email' value='' class='user_field' placeholder='example@email.com'></td>
        </tr>
        <tr>
          <td><p class='info'>Password:</p></td>
          <td><input type='password' name='password' value='' class='user_field' placeholder='8 characters or more'></td>
        </tr>

      </table>
      <input type='submit' value='Register' class='login_button'>
    </form>
    {% if messages %}
      {% for message in messages %}
      <div class='message_box red'>
          <p class='message'>{{ message }}</p>
      </div>
      {% endfor %}
    {% endif %}
  </div>
</body>
</html>

apps/users/templates/users/user_page.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'users/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<a href="{% url 'books:add' %}" class='book add_book_link'>Add Book and Review</a>
<a href="{% url 'books:home' %}" class='book add_book_link home'>Home</a>
<div class='header'>
  <form action='/logout'>
    <input type='submit' class='sign_out_button' value='Sign Out'>
  </form>
</div>
<body>

<div class='recents_box'>
  <h3 class='greeting'>Username: {{user.username}}</h3>
  <h3 class='greeting'>Name: {{user.first_name}} {{user.last_name}}</h3>
  <h3 class='greeting'>Email: {{user.email}}</h3>
  <h3 class='greeting'>Number of reviews: {{ review_count }}</h3>

  <h4 class='greeting'>Posted reviews on the following books:</h2>
  {% for review in user_reviews %}
    <a href="{% url 'books:bookPage' id=review.book.id %}" class='book_link post_link'>{{review.book.title}}</a>
  {% endfor %}
</div>
</body>
</html>