apps/travels/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.index, name='home'),
  url(r'^add$', views.add_travel, name='addPlans'),
  url(r'^(?P<id>\d+)/submit_travel$', views.submit_travel, name='submitTravels'),
  url(r'^destination/(?P<id>\d+)$', views.show_destination, name='travelPage'),
  url(r'^destination/(?P<id>\d+)/addUser$', views.add_user, name='addUser'),
]

apps/users/urls.py
from django.conf.urls import url
from . import views

app_name='users'
urlpatterns = [
  url(r'^$', views.index, name='home'),
  url(r'^log_in$', views.log_in, name='login'),
  url(r'^logout$', views.logout, name='logout'),
  url(r'^register$', views.register, name='register'),
  url(r'^register/add_user$', views.add_user, name='addUser'),
  url(r'^users/(?P<id>\d+)$', views.show_user, name='user'),
]

beltExam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^travels/', include('apps.travels.urls', namespace='travel')),
    url(r'^admin/', admin.site.urls),
]

apps/travels/models.py
from __future__ import unicode_literals
from django.db import models
from ..users.models import User
import datetime

# Create your models here.
class TravelManager(models.Manager):
  def makeTravel(self, postData, user):
    travel_validation = {
      'isValid': True,
      'errors': [],
      'travel': None
    }

    
    dest = str(postData['destination'])
    desc = str(postData['description'])
    start = postData['start']
    end = postData['end']
 
    if(len(dest)==0):
      travel_validation['isValid'] = False
      travel_validation['errors'].append("Please enter a destination")
      
    if(len(desc)==0):
      travel_validation['isValid'] = False
      travel_validation['errors'].append("Please enter a description")

    time = datetime.datetime.now()
    time = [time.year, time.month, time.day]
    if(not self.validateTime(start, time)):
      travel_validation['isValid'] = False
      travel_validation['errors'].append("Please enter a valid start date")

    time = [start[0:4], start[5:7], start[8:10]]
    if(not self.validateTime(end, time)):
      travel_validation['isValid'] = False
      travel_validation['errors'].append("Please enter a valid end date")

    if(travel_validation['isValid']):
      start = start[0:10]
      print(start)
      travel = Travel.objects.create(destination=dest, plans=desc, user=user, start=start[0:10], end=end[0:10])
      travel_validation['travel']=travel


    return travel_validation

  def validateTime(self, time1, time2):
    try:
      start_y = int(time1[0:4])
      start_m = int(time1[5:7])
      start_d = int(time1[8:10])

      year = int(time2[0])
      month = int(time2[1])
      day = int(time2[2])
  
      if(start_y < year):
        return False

      elif(start_y == year):
        if(start_m < month):
          return False     

        elif(start_m == month):
          if(start_d <= day):
            return False 

      return True       
  
    except:
      return False

  def addUserToTravel(self, travel_id, user_id):
    travel = Travel.objects.get(id=travel_id)
    user = User.objects.get(id=user_id)
    user_joined = False
   
    joined_users = JoinedUser.objects.filter(travel=travel)
    for join in joined_users:
      if user.id == join.user.id:
        user_joined = True

    if(not user_joined):
      JoinedUser.objects.create(travel=travel, user=user)


class Travel(models.Model):
  destination = models.CharField(max_length=100)
  plans = models.TextField(max_length=1000)
  user = models.ForeignKey(User)
  start = models.DateField()
  end = models.DateField()
  objects = TravelManager()
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  def joinedUsers(self):
    user_ids = []

    joins = JoinedUser.objects.filter(travel=self)
    for join in joins:
      user_ids.append(join.user.id)

    return user_ids

class JoinedUser(models.Model):
  travel = models.ForeignKey(Travel)
  user = models.ForeignKey(User)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

apps/travels/views.py
from django.shortcuts import render, reverse, redirect
from ..users.models import User
from .models import Travel, JoinedUser
from django.contrib import messages
# Create your views here.
#Travel.objects.get(destination='Montana').delete()
def index(request):
    if(not check_user_authentication(request)):
      return redirect('users:home')

    user = User.objects.get(id=request.session['user_id'])

    context = {
      'user': user,
      'myTravels': Travel.objects.filter(user=user),
      'myJoinedTravels': JoinedUser.objects.filter(user=user),
      'otherTravels': Travel.objects.exclude(user=user).order_by('start'),
    }

    return render(request, "travels/index.html", context)

def add_travel(request):
    if(not check_user_authentication(request)):
      return redirect('users:home')

    context = {
      'user': User.objects.get(id=request.session['user_id'])
    }

    return render(request, "travels/add_travel.html", context)

def submit_travel(request, id):
    if(not check_user_authentication(request)):
      return redirect('users:home')

    postData = dict(request.POST.items())

    travel_valid = Travel.objects.makeTravel(postData, User.objects.get(id=request.session['user_id']))

    if(not travel_valid['isValid']):
      for error in travel_valid['errors']:
        messages.add_message(request, messages.INFO, error)

      return redirect('travel:addPlans')

    else:
      return redirect('travel:home')

def show_destination(request, id):
    if(not check_user_authentication(request)):
      return redirect('users:home')

    travel = Travel.objects.get(id=id)
    joiners = JoinedUser.objects.filter(travel=travel)
    context = {
      'travel' : travel,
      'joiners': joiners,
    }

    return render(request, 'travels/show_travel.html', context)

def add_user(request, id):
    if(not check_user_authentication(request)):
      return redirect('users:home')

    travel = Travel.objects.get(id=id)
    user = User.objects.get(id=request.session['user_id'])

    Travel.objects.addUserToTravel(travel.id, user.id)

    return redirect('travel:home')

def check_user_authentication(request):
    try:
      if(request.session['user_logged']):
        user_id = request.session['user_id']
        return True
      else:
        return False
    except:
      return False

apps/travels/templates/travels/add_travel.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'travels/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
<form action="{% url 'users:logout' %}">
  <input type='submit' value='Sign Out'>
</form>
<a href="{% url 'travel:home' %}">Home</a>

<form action="{% url 'travel:submitTravels' id=user.id %}" method='post'>
{% csrf_token %}
  <table>
    <tr>
      <td>Destination:</td>
      <td><input type='text' name='destination'></td>
    </tr>
    <tr>
      <td>Description:</td>
      <td><input type='text' name='description'></td>
    </tr>
    <tr>
      <td>Travel Date Start:</td>
      <td><input type='date' name='start'></td>
    </tr>
    <tr>
      <td>Travel Date End:</td>
      <td><input type='date' name='end'></td>
    </tr>

  </table>
  <input type='submit' value='Add'>
</form>
{% if messages %}
  {% for message in messages %}
    <p>{{message}}</p>
  {% endfor %}
{% endif %}
</body>
</html>

apps/travels/templates/travels/index.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'travels/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
<h2>Hello, {{user.first_name}}</h2>
<form action="{% url 'users:logout' %}">
  <input type='submit' value='Sign Out'>
</form>

<h4>Your trip schedules:</h4>
<table style='padding: 30px;'>
  <thead>
    <th>Destination</th>
    <th>Travel Start Date</th>
    <th>Travel End Date</th>
    <th>Plan</th>
  </thead>

  <tbody>
    {% for travel in myTravels %}
      <tr>
        <td><a href="{% url 'travel:travelPage' id=travel.id %}">{{travel.destination}}</a></td>
        <td>{{travel.start}}</td>
        <td>{{travel.end}}</td>
        <td>{{travel.plans}}</td>
      </tr>
    {% endfor %}
    {% for join in myJoinedTravels %}
      <tr>
        <td><a href="{% url 'travel:travelPage' id=join.travel.id %}">{{join.travel.destination}}</a></td>
        <td>{{join.travel.start}}</td>
        <td>{{join.travel.end}}</td>
        <td>{{join.travel.plans}}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<h4>Other trip schedules:</h4>
<table style='padding: 30px;'>
  <thead>
    <th>Name</th>
    <th>Destination</th>
    <th>Travel Start Date</th>
    <th>Travel End Date</th>
    <th>Plan</th>
    <th>Do you wanna join?</th>
  </thead>

  <tbody>
    {% for travel in otherTravels %}
      {% if user.id not in travel.joinedUsers%}
        <tr>
          <td>{{travel.user.first_name}}</td>
          <td><a href="{% url 'travel:travelPage' id=travel.id %}">{{travel.destination}}</a></td>
          <td>{{travel.start}}</td>
          <td>{{travel.end}}</td>
          <td>{{travel.plans}}</td>
          <td><a href="{% url 'travel:addUser' id=travel.id %}">Join</a><td>
        </tr>
      {% endif %}
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'travel:addPlans' %}">Add travel plans!</a>
</body>
</html>

apps/travels/templates/travels/show_travel.html
<!DOCTYPE html>

<html>
<head>
  <meta charset="utf-8">
  <title>BLANK_TITLE</title>
  <meta name="description" content="BLANK DESCRIPTION">
  {% load static %}
  <link rel="stylesheet" href="{% static 'travels/css/main.css'%}" media="screen" title="no title"  charset="utf-8">
</head>
<body>
<form action="{% url 'users:logout' %}">
  <input type='submit' value='Sign Out'>
</form>
<a href="{% url 'travel:home' %}">Home</a>

<h1>{{travel.destination}}</h1>
<p> Planned by: {{travel.user.first_name}} {{travel.user.last_name}} </p>
<p> Description: {{travel.plans}}</p>
<p> Travel Start date: {{travel.start}}</p>
<p> Travel End date: {{travel.end}}</p>

<h3>Other people joining: </h3>
{% for joiner in joiners %}
  <p> {{joiner.user.first_name}} {{joiner.user.last_name}}</p>
{% endfor %}
</body>
</html>